### ISSUE TITLE
Text is invisible in night mode, Categories are whited out in any mode.

### ISSUE THREAD

**Issue by yoshi314** [my-Anki/Beautify-Anki#1]
Titles of decks that include sub-decks are white-on-white. 

In night mode, all deck names are invisible. Disabling night mode makes things partially usable. Might be the choice of system color theme on my end.

**Comment by ShoroukAziz** [comment]
support for night mode and total complete over the text color will be available in the coming update

**Comment by PhongTong** [comment]
![image](https://user-images.githubusercontent.com/8979366/83948106-3b572c80-a845-11ea-8543-7659b1145b48.png)

![image](https://user-images.githubusercontent.com/8979366/83948162-aef93980-a845-11ea-81ee-66c1e2d6211d.png)

Sorry for opening this issue again. But right now, the color text is black on night background
