### ISSUE TITLE
visual problems

### ISSUE THREAD

**Issue by apatrickeisenberg** [my-Anki/Beautify-Anki#13]
The statistics are not fitting inside their boxes and when I open a deck to start doing cards the configuration is off. Does this add on not play well with Anking's background image customizer?

![image](https://user-images.githubusercontent.com/65625084/82371185-bddb9180-99e7-11ea-9c4d-aa91be0e12c1.png)

![image](https://user-images.githubusercontent.com/65625084/82371215-cfbd3480-99e7-11ea-9986-dbc994260dda.png)

**Comment by ShoroukAziz** [comment]
I don't have Anking's background image customizer so try disabling it and let me know if it's what's causing the problem.
As for the second picture refer to #3

**Comment by apatrickeisenberg** [comment]
I tried disabling it, and the text on the front screen turned white and i
couldn’t see it, but it didn’t change the problems in the stats. I coded
the Anking thing to make the front page text that neon color so that’s why
it’s neon pink

**Comment by ShoroukAziz** [comment]
Ok, the white on white problem seems to be happening with lots of people. So, a fix will be included in the next update (probably an option to control the font color of the decks ).
I'll see what I can do about the stats not fitting too.
Thanks for letting me know.

**Comment by apatrickeisenberg** [comment]
Thank you for being so quick to respond. Overall this is an amazing add-on
and once the bugs get fixed it will be just absolutely phenomenal. I love
the statistics on the side

**Comment by ShoroukAziz** [comment]
fixed in the upcoming update
