### ISSUE TITLE
Cannot do filtered decks

### ISSUE THREAD

**Issue by ConsciousTechnology1** [my-Anki/Beautify-Anki#16]
There is no option to "Study" when you make a filtered deck.

**Comment by ShoroukAziz** [comment]
Hi, Thank you for reporting this bug. It's fixed now on GitHub 5ba4867.
You can either download the addon from here now or wait for the official update on Ankiweb.

**Comment by ConsciousTechnology1** [comment]
how do I download the addon from here? I am on a chromebook and downloaded anki through Linux.
