### ISSUE TITLE
Problème d'affichage

### ISSUE THREAD

**Issue by Jacques26** [my-Anki/Beautify-Anki#17]
Bonjour
Il y a un problème d'affichage au niveau des blocs de droite.
Comment faire pour avoir un affichage correcte ?
Cordialement.
![Annotation 2020-05-25 175845](https://user-images.githubusercontent.com/65912485/82828484-72c2f200-9eb1-11ea-9204-13529b6f0e0c.jpg)

**Comment by ShoroukAziz** [comment]
Bonjour,
Certaines personnes ont le même problème, et je vais travailler sur la correction. Pardonnez mon mauvais français je suis debutante!

**Comment by Jacques26** [comment]
Bonjour,

Mon anglais n’est pas bon aussi.

Merci pour votre travail

 

Cordialement

 

 

De : Shorouk Abdelaziz <notifications@github.com> 
Envoyé : mardi 26 mai 2020 21:01
À : my-Anki/Beautify-Anki <Beautify-Anki@noreply.github.com>
Cc : Jacques26 <carjc.2012@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [my-Anki/Beautify-Anki] Problème d'affichage (#17)

 

Bonjour,
Certaines personnes ont le même problème, et je vais travailler sur la correction. Pardonnez mon mauvais français je suis debutante!

**Comment by ShoroukAziz** [comment]
fixed in the upcoming update
