### ISSUE TITLE
Visual problems

### ISSUE THREAD

**Issue by OliverLiebmann** [my-Anki/Beautify-Anki#18]
In the deckoverview, the font is not displayed correctly, maybe my system doesn't include this font. So a font stack would probably be best. 
Furthermore the text is not centered in the buttons.
![Font Example](https://user-images.githubusercontent.com/19376062/83144865-3cc18000-a0f4-11ea-9b39-ca4f9ba1884f.png)

**Comment by ShoroukAziz** [comment]
I'll add an option to change the font in the next update.
However, You can fix it now by going to 
Addon folder > assets > css > overview.css
find that line 
`  font-family: fantasy;
`
and delete it.

Regarding the buttons, They are supposed to be aligned. have you updated the addon to version 0.2.0 ?
