### ISSUE TITLE
A few visual problems

### ISSUE THREAD

**Issue by RT94** [my-Anki/Beautify-Anki#21]
Hey @ShoroukAziz! I really love this addon. It is really refreshing to open anki with a new look and I appreciate all the work you have put into this addon. I have 3 visual issues I wanted to bring to your attention:

1.  When I click on a deck and I am in the deck overview, the text for the stats is not centered in the boxes and the review heatmap in the deck overview shows black text instead of white like it does on the main screen
![image](https://user-images.githubusercontent.com/64577185/83806661-def6e000-a67f-11ea-841c-c31d9836f6da.png)

2. There is a large gray box at the bottom of the main home screen when I expand the decks in my collection
![image](https://user-images.githubusercontent.com/64577185/83806882-2a10f300-a680-11ea-9d6c-65b942f6bb80.png)

3. When I go into Anki's main settings and change the zoom, I see some gray bars that are not there when the zoom is set to the normal 100%

100% zoom
![image](https://user-images.githubusercontent.com/64577185/83807036-693f4400-a680-11ea-9991-bd9c1a52868a.png)

125% zoom
![image](https://user-images.githubusercontent.com/64577185/83807359-f71b2f00-a680-11ea-82d7-ec587ea95761.png)

Please let me know if you need anything from me

**Comment by coolbeanz10101010** [comment]
hey how did you change the color of your stats area next to your main deck page??

**Comment by RT94** [comment]
> hey how did you change the color of your stats area next to your main deck page??

I'm not sure what you mean haha. I only changed the config to one of the preinstalled themes. It's called "starry"

**Comment by RT94** [comment]
So I'm guessing that there's no more support for this add-on? I haven't heard anything for a couple of months now

**Comment by RT94** [comment]
@ShoroukAziz So I'm guessing that there's no more support for this add-on? I haven't heard anything for a couple of months now

**Comment by ShoroukAziz** [comment]
@RT94 
Hi, sorry for the late reply
I'm currently working on an update to work with 2.1.30 , and I'll be fixing as many visual errors as possible too
