### ISSUE TITLE
exit_to_app Study Now

### ISSUE THREAD

**Issue by mateus2k2** [my-Anki/Beautify-Anki#22]
Weird text on Study Now button, the first image is with the More Overview Stats 2.1 enabled the second is with it disabled. Maybe has something to do with line 72 on the deck_overview.py file (?)

        `    '''.format(button=button('study', _('<i class=\"  material-icons right\">exit_to_app</i>  Study Now'), id='study', class_='waves-effect waves-light btn-large', extra='style=\'background:{THEME[buttons-color]}\''.format(THEME=THEME)))
`

![2020-06-15 14_18_08-ENEM - Anki](https://user-images.githubusercontent.com/24702324/84687209-b68aa380-af13-11ea-8ab3-44159696506d.png)
![2020-06-15 14_21_08-ENEM - Anki](https://user-images.githubusercontent.com/24702324/84687211-b7bbd080-af13-11ea-87a9-fdde60681ba2.png)

Thanks for the amazing job.

**Comment by ShoroukAziz** [comment]
hi,
you are using on of the conflicting add-ons mentioned here
https://beautify-anki.shorouk.dev/before-install
please disable it first
