### ISSUE TITLE
Having trouble downloading, error message

### ISSUE THREAD

**Issue by cb0321** [my-Anki/Beautify-Anki#24]
![image](https://user-images.githubusercontent.com/67469185/85859987-0840f280-b78c-11ea-8c24-96d7d47c4d0a.png)

I get an error message saying "Error downloading 1150874988: INvalid code, or add-on not available for your version of Anki"

What do I do? Apparently I have version 2.1.5, but I uninstalled to download 2.1.26 again yet got the same message. Really want to use this add-on and would appreciate any help.

**Comment by vietkutie001** [comment]
Hi there, I have version 2.1.28 and I am having the same issue. Is it being looked after, or is there a status update available? I see that @cb0321 made this post two months ago. Thanks in advance! 
<img width="435" alt="Screen Shot 2020-08-23 at 2 48 37 PM" src="https://user-images.githubusercontent.com/70113425/90988649-b92bf980-e551-11ea-8baa-5e7d34136087.png">

**Comment by ShoroukAziz** [comment]
Try this version please 
https://github.com/my-Anki/Beautify-Anki/releases/tag/v.0.3.2
it's compatible with v2.1.30+
