### ISSUE TITLE
Stats area not changing color?

### ISSUE THREAD

**Issue by coolbeanz10101010** [my-Anki/Beautify-Anki#25]
Changed colors in "default" theme and top/bottom bar with large areas color changed but the wedgits did not

**Comment by ShoroukAziz** [comment]
could you post screenshots of your config file and your Anki?

**Comment by coolbeanz10101010** [comment]
![Screen Shot 2020-08-16 at 11 28 29 AM](https://user-images.githubusercontent.com/62732414/90339357-dbec6a00-dfb5-11ea-9892-26730117da31.png)
![Screen Shot 2020-08-16 at 11 29 23 AM](https://user-images.githubusercontent.com/62732414/90339361-df7ff100-dfb5-11ea-9c37-9a67d2cf9559.png)

**Comment by coolbeanz10101010** [comment]
I am happy with it now, i just want to be able to change the green and blue count colors ...

**Comment by ShoroukAziz** [comment]
you will be able to do so the next update which will be out in a few of days
