### ISSUE TITLE
Deck Overview Not Working

### ISSUE THREAD

**Issue by amohan12** [my-Anki/Beautify-Anki#26]
Love the theme however when I click any of my decks, I dont get a Deck Overview Page. Instead I get something that looks like this: 
![image](https://user-images.githubusercontent.com/49009685/86805589-ff7ed500-c045-11ea-9040-8eeee5ad67f1.png)

**Comment by ShoroukAziz** [comment]
could you please make sure you're not using any of the conflicting add-ons mentioned here
https://beautify-anki.shorouk.dev/before-install
and let me know then
