### ISSUE TITLE
Widget Images Missing!

### ISSUE THREAD

**Issue by Rellovrollover** [my-Anki/Beautify-Anki#27]
![For GitHub](https://user-images.githubusercontent.com/68078729/87077618-4e319800-c21b-11ea-921e-2eac24226c15.png)

Hi,

Hoping someone can help:

I'm having an issue with the CSS widgets not showing. Attached is an image of the missing widgets on the home page and also the .json file for that theme showing. All widgets are not showing, including the ones at the bottom bar and in the deck overview page.

Thanks,
Rellov

**Comment by ShoroukAziz** [comment]
Hi there,
Thanks for reaching out and sorry for the late replay.
I don't really know what's causing this, but the upcoming update (3 or 4 days)  uses a completely different way of dealing with icons.
