### ISSUE TITLE
Feature Request: Option to Move Review Heatmap on Main Screen

### ISSUE THREAD

**Issue by oooooooooooooooo** [my-Anki/Beautify-Anki#28]
**1. Option to move review heatmap to the right below widgets so that everything can be viewed at a glance (May require shifting deck object slightly to the left**

![Screenshot (109)](https://user-images.githubusercontent.com/8386495/87883807-396ab680-ca0a-11ea-9cdd-90d394ae56da.png)
![Screenshot (108)](https://user-images.githubusercontent.com/8386495/87883808-3cfe3d80-ca0a-11ea-8f52-2bf805055ac4.png)

**Comment by ShoroukAziz** [comment]
that's legit. will take it into consideration
