### ISSUE TITLE
Decks have default UI

### ISSUE THREAD

**Issue by Kiwlo** [my-Anki/Beautify-Anki#3]
When I go into any deck, it looks how it normally would on Anki except for some weird text, the main screen however looks normal
![Main screen](https://user-images.githubusercontent.com/65585820/82287962-66014400-996f-11ea-8874-4dbe1e98378c.png)
![In deck](https://user-images.githubusercontent.com/65585820/82287986-76192380-996f-11ea-8674-ec24fd773a00.png)

**Comment by ShoroukAziz** [comment]
that did happen with me when I was using an unofficial version of Review Heatmap. if you are, please install it from here https://github.com/glutanimate/review-heatmap/releases and disable the version you have. If you're using the official version let me know

**Comment by Kiwlo** [comment]
Thank you, this fixed the issue

**Comment by ShoroukAziz** [comment]
Great, You are welcome!
