### ISSUE TITLE
Font diffuclties

### ISSUE THREAD

**Issue by Rivents** [my-Anki/Beautify-Anki#31]
First of all, thanks so much for creating this add-on, its been pretty lovely setting up! 
This might be a minor issue that other people haven't seemed to have trouble with, but Ive had a problem figuring out how to change the font on the Deck summary page, it gets quite big, causing it to wrap around, and is in a different font then the ones in other's screenshots. Any idea how I would be able to change that?
There is also a white band at the bottom of the deck summary screen that I also had difficulty correcting. 
I don't have much experience with coding unfortunate, but I would appreciate any help you could provide!
Thank you so much

<img width="1280" alt="Screen Shot 2020-07-25 at 11 50 04 PM" src="https://user-images.githubusercontent.com/68799365/88471020-9a463300-ced1-11ea-8f76-38bab578540a.png">

**Comment by ShoroukAziz** [comment]
Hi, thanks for reaching out!
I'm working on an update that will let you easily change the font-family and font size through the config file directly.
