### ISSUE TITLE
Bottom bar color doesn't change

### ISSUE THREAD

**Issue by achen898** [my-Anki/Beautify-Anki#32]
When I go in to edit the bottom bar color it won't change for some reason, but the top bar color changes just fine.

Also not sure if this is an appropriate way to ask this but is there a way to change the "+" colors when expanding the decks, along with the colors of the number of new/review cards that  show up? Thanks!

![image](https://user-images.githubusercontent.com/64118247/88843277-b37f0600-d195-11ea-9eeb-598ac0729b60.png)
![image](https://user-images.githubusercontent.com/64118247/88843297-ba0d7d80-d195-11ea-93bb-4d9a1412b747.png)

**Comment by ShoroukAziz** [comment]
Thanks for reporting this. It was a bug in the night mode and is fixed in the upcoming update.
Also, the + and the new/review colors will be totally customizable too.
