### ISSUE TITLE
Cannot Download Add on 

### ISSUE THREAD

**Issue by sharion64** [my-Anki/Beautify-Anki#33]
![image](https://user-images.githubusercontent.com/55957877/89183712-8c5a7700-d58f-11ea-985a-776cb031ba1c.png)

**Comment by BenRGH** [comment]
I also have this issue, running latest 2.1.30

**Comment by ShoroukAziz** [comment]
current support is for version 2.1.26
an update that supports version 2.1.30 will be released in a few days among other bug fixes.
