### ISSUE TITLE
Loading error with latest anki 2.1.33 using Anki Beautify 0.3.0 update.

### ISSUE THREAD

**Issue by palosbuenos** [my-Anki/Beautify-Anki#39]
This is a fantastic add on by the way and should be preloaded with anki. It really changes the whole appearance and feel of anki, it feels like a modern 21st century program and far surpasses the "customise background image" which I previously used.

Anyway.

Error everytime on loading anki. The add-on still manages to load but gives the error below. 
The studied cards, average cards/minute, etc column is incorrectly positioned as whole bars at the bottom of the screen, rather than compact buttons positioned to the right of the topic/study lists (which are at top)

Also is it possible to get everything to fit on the main screen when using font enlarger? I need it for the cards.

Here are some screen shots to explain.

![2020-09-12_11-43-05](https://user-images.githubusercontent.com/70043582/92984934-5b098b00-f4ed-11ea-99ab-33ef5e73f03c.png)
![2020-09-12_11-44-04](https://user-images.githubusercontent.com/70043582/92984936-60ff6c00-f4ed-11ea-829b-cfe626b5bbe2.png)

Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-11 22:17:33
Add-ons possibly involved: ⁨Beautify-Anki⁩

Traceback (most recent call last):
  File "aqt/main.py", line 521, in loadCollection
  File "aqt/main.py", line 661, in moveToState
  File "aqt/main.py", line 668, in _deckBrowserState
  File "aqt/deckbrowser.py", line 58, in show
  File "aqt/deckbrowser.py", line 115, in _renderPage
  File "aqt/deckbrowser.py", line 124, in __renderPage
  File "aqt/webview.py", line 378, in stdHtml
  File "aqt/gui_hooks.py", line 2917, in __call__
  File "/Users/paul/Library/Application Support/Anki2/addons21/Beautify-Anki/__init__.py", line 80, in on_webview_will_set_content
    web_content.css.remove("deckbrowser.css")
ValueError: list.remove(x): x not in list

**Comment by palosbuenos** [comment]
ok. turned out the issue was with 2 things:

the default theme (which seems to bug out- but I used flamingo theme which worked perfect
and also the add-on "set font size" this is not compatible with anki-beautify.

**Comment by ShoroukAziz** [comment]
Thanks so much.
I'll add this addon to the list of conflicting ones.
also would be great if you can try the new version and give your feedback
https://github.com/my-Anki/Beautify-Anki/releases/tag/v.0.3.2

**Comment by Paul-Zhu-Fong** [comment]
The issues still isn't resolved with the newest version. I'm having the exact same problem
