### ISSUE TITLE
CPU usage spikes really high on image cycle

### ISSUE THREAD

**Issue by Kiwlo** [my-Anki/Beautify-Anki#4]
I don't know if this is an issue caused by my images specifically, but whenever the cycle occurs the usage on my CPU (Ryzen 2700x, so that is not the problem) spikes to 60%.
![image](https://user-images.githubusercontent.com/65585820/82293755-0c9f1200-997b-11ea-92fb-58c646806b3a.png)

**Comment by ShoroukAziz** [comment]
Chapeau for noticing!
This will either be fixed or an option to turn the animation off will be added

**Comment by ShoroukAziz** [comment]
Hi again,
This is highly improved now that the images have been optimized. The smaller the size of the images you're using the less CPU is being used. Also, an option to stop the animation has been added and will be included in the next official update on Ankiweb.
