### ISSUE TITLE
Loading error with Version 2.1.35

### ISSUE THREAD

**Issue by KatharinaBuck** [my-Anki/Beautify-Anki#40]
**Describe the bug**
Unfortunately I can't load this beautiful Add-On for my current Anki Version 2.1.35 since I get an error message instead.
<img width="419" alt="Screenshot 2020-10-16 at 21 53 15" src="https://user-images.githubusercontent.com/13108211/96303011-011f4800-0ffa-11eb-8e63-e012fbe463ba.png">

 - OS: 10.15.5
 - Anki Version 2.1.35

**Comment by ShoroukAziz** [comment]
This release will work
https://github.com/my-Anki/Beautify-Anki/releases/tag/v.0.3.2
