### ISSUE TITLE
Change Front size 

### ISSUE THREAD

**Issue by dksdjadaj** [my-Anki/Beautify-Anki#45]
Hi, im not sure why my front is like this. Also, I don't know how to change the color in the wheel to make it more read-able

<img width="1314" alt="Screen Shot 2020-10-29 at 4 09 08 PM" src="https://user-images.githubusercontent.com/73668366/97627297-8e529b80-1a01-11eb-9848-73ce77a7a9d9.png">

**Comment by ShoroukAziz** [comment]
Open the theme JSON file of the theme you're using 
under Deck overt view
```
    "DECK-OVERVIEW" :{

        "deck-name-font-size":"70px",
        "deck-name-font-family":"fantasy",
        "deck-name-font-src"        :"",

        "wedgits-font-size"     :"13px",
        "wedgits-font-family"   :"Raleway",
        "wedgits-font-src"      :"Raleway.ttf",
        "wedgits-font-color"    : "rgba(255, 255, 255,1)",


        "total-notes-wedgit-bg" : "rgba(0, 96, 100,1)" ,
        "remaining-wedgit-bg"   : "rgba(245, 127, 23,1)" ,
        "new-wedgit-bg"         : "rgba(1, 87, 155,1)" ,
        "learning-wedgit-bg"    : "rgba(191, 54, 12,1)" ,
        "review-wedgit-bg"      : "rgba(27, 94, 32,1)" ,
        "total-wedgit-bg"       : "rgba(49, 27, 146,1)" ,

        


    
    
    "PIE-CHART":{
        "wedgits-font-color" : "rgba(255, 255, 255,1)"

    }
    }

}
```

 find and change these value 
 font size and font family to whatever you want
```
   "deck-name-font-size":"70px",
   "deck-name-font-family":"fantasy",
```
and under PIE-CHART change `   "wedgits-font-color" 

`I'll add detailed steps in the docs so soon

**Comment by dksdjadaj** [comment]
Hi, I try doing that but it still didn't work.
<img width="491" alt="Screen Shot 2020-10-30 at 2 31 51 PM" src="https://user-images.githubusercontent.com/73668366/97743876-b226e780-1abc-11eb-9203-7e4a1026775c.png">

<img width="1289" alt="Screen Shot 2020-10-30 at 2 29 20 PM" src="https://user-images.githubusercontent.com/73668366/97743887-b3f0ab00-1abc-11eb-8c70-cf8a7c8927e3.png">
