### ISSUE TITLE
How to make Beautify-Anki working on Anki 2.1.35

### ISSUE THREAD

**Issue by ebanDev** [my-Anki/Beautify-Anki#47]
**Before posting, please verify that you've done the following** 
* [x] read the ["before you install instructions"](https://beautify-anki.shorouk.dev/before-install) and disabled all the known conflicted add-ons.
* [x] You've looked through previous issues to see if someone else had the same problem.

**Describe the bug**
I actually can't add Beautify-Anki to Anki 2.1.35 :/

**Contex (please complete the following information):**
 - OS: Debian 10 (Linux)
 - Anki Version 2.1.35

**Comment by cereska** [comment]
@ebanDev the version on the addon gallery is not compatible with 2.1.35. 
What you can do in the meantime, before the new version is released, is to install a beta of a new version found here: https://github.com/my-Anki/Beautify-Anki/releases/tag/v.0.3.2 
Just extract the archive to your addon folder and rename it to BeautifyAnki (no spaces, no special characters etc) and restart Anki.

**Comment by ebanDev** [comment]
Okay, thanks !
