### ISSUE TITLE
The mouse pointer is out of position (+) to open the subdecks

### ISSUE THREAD

**Issue by cjdduarte** [my-Anki/Beautify-Anki#7]
![sample](https://user-images.githubusercontent.com/42243532/82325892-58b97900-99b2-11ea-9408-8a13f2b1b711.gif)

**Comment by ShoroukAziz** [comment]
That will need fixing. thanks for reporting

**Comment by ShoroukAziz** [comment]
Hi,
This is now fixed 01b09a1 and will be included in the next official update. Thanks again for reporting it
